name: SDK Release

on:
  pull_request:
    branches: [ master ]
    types: [ closed ]

permissions:
  contents: write
  packages: write

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:

      - name: Checkout (commit mergeado)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}

      - name: Dar permiss√£o ao Gradle Wrapper
        run: chmod +x gradlew

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Ler vers√£o do version.properties
        id: version
        run: |
          VERSION=$(grep VERSION_NAME version.properties | cut -d'=' -f2)
          echo "versao=$VERSION" >> $GITHUB_OUTPUT
          echo "Vers√£o lida: $VERSION"

      - name: Criar tag
        run: |
          TAG=v${{ steps.version.outputs.versao }}

          if git rev-parse "$TAG" >/dev/null 2>&1 ; then
            echo "Tag $TAG j√° existe, ignorando cria√ß√£o."
            exit 0
          fi

          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git tag -a "$TAG" -m "Release $TAG"
          git push origin "$TAG"

      - name: Criar Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.versao }}
          name: Release v${{ steps.version.outputs.versao }}
          body: |
            üöÄ Nova vers√£o publicada automaticamente!
            ‚Ä¢ PR: #${{ github.event.pull_request.number }}
            ‚Ä¢ Vers√£o: **${{ steps.version.outputs.versao }}**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publicar no GitHub Packages
        run: ./gradlew publish
        env:
          VERSION_NAME: ${{ steps.version.outputs.versao }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
